//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WPF_InhouseLab.Ressources.Loc {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class PersonenDialog_Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PersonenDialog_Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WPF_InhouseLab.Ressources.Loc.PersonenDialog_Strings", typeof(PersonenDialog_Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abbruch.
        /// </summary>
        public static string Btn_Abbruch_Content {
            get {
                return ResourceManager.GetString("Btn_Abbruch_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string Btn_Ok_Content {
            get {
                return ResourceManager.GetString("Btn_Ok_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deutsch.
        /// </summary>
        public static string Mit_Deutsch_Header {
            get {
                return ResourceManager.GetString("Mit_Deutsch_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Englisch.
        /// </summary>
        public static string Mit_Englisch_Header {
            get {
                return ResourceManager.GetString("Mit_Englisch_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sprache.
        /// </summary>
        public static string Mit_Sprache_Header {
            get {
                return ResourceManager.GetString("Mit_Sprache_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Divers.
        /// </summary>
        public static string Rbt_D_Content {
            get {
                return ResourceManager.GetString("Rbt_D_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Männlich.
        /// </summary>
        public static string Rbt_M_Content {
            get {
                return ResourceManager.GetString("Rbt_M_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weiblich.
        /// </summary>
        public static string Rbt_W_Content {
            get {
                return ResourceManager.GetString("Rbt_W_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geburtsdatum:.
        /// </summary>
        public static string Tbl_Geburtsdatum_Text {
            get {
                return ResourceManager.GetString("Tbl_Geburtsdatum_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geschlecht:.
        /// </summary>
        public static string Tbl_Geschlecht_Text {
            get {
                return ResourceManager.GetString("Tbl_Geschlecht_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kinder.
        /// </summary>
        public static string Tbl_Kinder_Text {
            get {
                return ResourceManager.GetString("Tbl_Kinder_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lieblingsfarbe:.
        /// </summary>
        public static string Tbl_Lieblingsfarbe_Text {
            get {
                return ResourceManager.GetString("Tbl_Lieblingsfarbe_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nachname:.
        /// </summary>
        public static string Tbl_Nachname_Text {
            get {
                return ResourceManager.GetString("Tbl_Nachname_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verheiratet:.
        /// </summary>
        public static string Tbl_Verheiratet_Text {
            get {
                return ResourceManager.GetString("Tbl_Verheiratet_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vorname:.
        /// </summary>
        public static string Tbl_Vorname_Text {
            get {
                return ResourceManager.GetString("Tbl_Vorname_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grün.
        /// </summary>
        public static string usedColors_0 {
            get {
                return ResourceManager.GetString("usedColors_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rot.
        /// </summary>
        public static string usedColors_1 {
            get {
                return ResourceManager.GetString("usedColors_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blau.
        /// </summary>
        public static string usedColors_2 {
            get {
                return ResourceManager.GetString("usedColors_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gelb.
        /// </summary>
        public static string usedColors_3 {
            get {
                return ResourceManager.GetString("usedColors_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Orange.
        /// </summary>
        public static string usedColors_4 {
            get {
                return ResourceManager.GetString("usedColors_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lila.
        /// </summary>
        public static string usedColors_5 {
            get {
                return ResourceManager.GetString("usedColors_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schwarz.
        /// </summary>
        public static string usedColors_6 {
            get {
                return ResourceManager.GetString("usedColors_6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weiß.
        /// </summary>
        public static string usedColors_7 {
            get {
                return ResourceManager.GetString("usedColors_7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Neue Person.
        /// </summary>
        public static string Wnd_Title {
            get {
                return ResourceManager.GetString("Wnd_Title", resourceCulture);
            }
        }
    }
}
